#!/bin/sh

/usr/bin/invoke_app "$@" -C "start_jupyter -t -T @tool brshores_notebook.ipynb" \
                        -t brshores_test \
                        -u anaconda3-5.1 \
                        -e TOOL_PYTHONPATH=/apps/share64/debian7/anaconda/anaconda3-5.1/tools/tellurium/20190823/lib/python3.6/site-packages
